name: pygada
channels:
- conda-forge
dependencies:
- fiona=1.8.22
- geocube=0.3.3
- geopandas=0.10.2
- ipython=8.11.0
- jupyter=1.0.0
- jupyterlab=3.6.1
- loguru=0.6.0
- matplotlib=3.6.1
- numpy=1.23.4
- OWSLib=0.27.2
- pandas=1.5.0
- pyproj=3.4.0
- rasterio=1.3.3
- scipy=1.9.1
- seaborn=0.11.2
- pip:
  - pydov[proxy]>=3.0.0
  - pysgems==1.2.3
